### ISSUE TITLE
Solving with 0.6 on  blender 2.76b leads always to bpy.app object has no attribute "build revision"

### ISSUE THREAD

**Issue by bachmarc** [stuffmatic/blam#15]
HI,
I just try to solve a simple example but it fails... minimalistic 2 lines in one greace pencil layer, one vanishing point (2 is not working either..)
no, not parallel lines ;o)...

 Traceback (most recent call last):
  File "C:\Users\d052074\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\blam.py", line 1950, in execute
    M = self.computeCameraRotationMatrix(Fu, Fv, f, P)
  File "C:\Users\d052074\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\blam.py", line 1661, in computeCameraRotationMatrix
    if arePythonMatricesRowMajor():
  File "C:\Users\d052074\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\blam.py", line 401, in arePythonMatricesRowMajor
    rev = bpy.app.build_revision
AttributeError: 'bpy.app' object has no attribute 'build_revision'

location: <unknown location>:-1

**Comment by bachmarc** [comment]
Ahh I have downloaded 0.5....
